name: Build & Deploy PDF

on:
  push:
    tags: '*'
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Tectonic
        uses: actions/cache@v1
        with:
          path: src/.cache
          key: tectonic
      - name: Build PDF
        run: make
      - name: Publish PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/*.pdf

